CREATE TYPE type_game AS ENUM (
    'Online',
    'Hotseat'
)

CREATE TYPE ox AS ENUM (
	'X',
	'O'
);

CREATE TYPE game_mode AS ENUM (
    'Fixed',
    'Infinity'
);

CREATE TYPE res_game AS ENUM (
	'WinX',
	'WinY',
	'Actual',
	'Draw',
    'Freeze'
);


CREATE TYPE pos AS (
	x INTEGER,
	y INTEGER
);


CREATE TYPE login AS (
	field VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS moves (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	owner LOGIN NOT NULL,
	coordinates POS NOT NULL,
	game BIGINT NOT NULL,
	date TIMESTAMPTZ NOT NULL,
	PRIMARY KEY(id)
);

CREATE UNIQUE INDEX moves_unique_cell_per_game
    ON moves (game, ((coordinates).x), ((coordinates).y));

CREATE TABLE IF NOT EXISTS games (
	id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	f_gamer LOGIN,
	s_gamer LOGIN,
	f_OX OX NOT NULL,
	result res_game NOT NULL,
    dimensions INTEGER NOT NULL DEFAULT 3,
    mode game_mode NOT NULL DEFAULT 'Fixed',
    type type_game NOT NULL DEFAULT 'Online',
	PRIMARY KEY(id),

    CONSTRAINT games_dimensions CHECK (dimensions > 0),
	CONSTRAINT games_distinct_players CHECK (f_gamer IS NULL OR s_gamer IS NULL OR f_gamer <> s_gamer)
);

CREATE TABLE IF NOT EXISTS gamers (
	login LOGIN NOT NULL UNIQUE,
	passwd VARCHAR(255) NOT NULL,
	level INTEGER NOT NULL,
	PRIMARY KEY(login),

	CONSTRAINT gamers_level_nonnegative CHECK (level >= 0)
);


CREATE INDEX "gamers->index->login"
ON gamers (login);
ALTER TABLE moves
ADD FOREIGN KEY(owner) REFERENCES gamers(login)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE games
ADD FOREIGN KEY(f_gamer) REFERENCES gamers(login)
ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE games
ADD FOREIGN KEY(s_gamer) REFERENCES gamers(login)
ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE moves
ADD FOREIGN KEY(game) REFERENCES games(id)
ON UPDATE CASCADE ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION delete_empty_games()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM games
    WHERE f_gamer IS NULL
      AND s_gamer IS NULL;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER gamers_delete_empty_games
AFTER DELETE ON gamers
FOR EACH ROW
EXECUTE FUNCTION delete_empty_games();
