CREATE TYPE type_game AS ENUM (
    'Online',
    'Hotseat'
);

CREATE TYPE ox AS ENUM (
	'X',
	'O'
);

CREATE TYPE game_mode AS ENUM (
    'Fixed',
    'Infinity'
);

CREATE TYPE res_game AS ENUM (
	'WinX',
	'WinO',
	'Actual',
	'Draw',
    'Freeze'
);


CREATE TABLE IF NOT EXISTS gamers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	level INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

	CONSTRAINT gamers_level_nonnegative CHECK (level >= 0)
);

CREATE TABLE IF NOT EXISTS games (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	f_gamer_id BIGINT,
	s_gamer_id BIGINT,
	f_OX OX NOT NULL,
    current_OX OX,
	result res_game NOT NULL,
    dimensions INTEGER NOT NULL DEFAULT 3,
    mode game_mode NOT NULL DEFAULT 'Fixed',
    type type_game NOT NULL DEFAULT 'Online',

    CONSTRAINT games_dimensions CHECK (dimensions > 0),

    CONSTRAINT games_first_gamer_fk
        FOREIGN KEY (f_gamer_id)
        REFERENCES gamers(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT games_second_gamer_fk
        FOREIGN KEY (s_gamer_id)
        REFERENCES gamers(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS moves (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
	played_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT moves_owner_fk
        FOREIGN KEY (owner_id)
        REFERENCES gamers(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT moves_game_fk
        FOREIGN KEY (game_id)
        REFERENCES games(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE OR REPLACE FUNCTION delete_empty_games()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM games
    WHERE f_gamer_id IS NULL
      AND s_gamer_id IS NULL;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER gamers_delete_empty_games
AFTER DELETE ON gamers
FOR EACH ROW
EXECUTE FUNCTION delete_empty_games();
